### ISSUE TITLE
websocket problems with 1.29.1 - optimisation

### ISSUE THREAD

**Issue by Brettdah** [Brettdah/vaultwarden-traefiked#3]
Web socket should be optimised after using 1.29.0 no more dedicated port nor network

``` yaml
version: '3.1'
# NETWORKS
networks:
  proxy:
    external: true
  proxy-internal:

#SERVICES
services:
  bitwarden:
    image: vaultwarden/server:1.27.0-alpine
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
        - traefik.http.routers.bitwarden-ui-https.rule=Host(`vault.home.tux4all.fr`)
        - traefik.http.routers.bitwarden-ui-https.entrypoints=https
        - traefik.http.routers.bitwarden-ui-https.tls=true
        - traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui
        - traefik.http.routers.bitwarden-ui-http.rule=Host(`vault.home.tux4all.fr`)
        - traefik.http.routers.bitwarden-ui-http.entrypoints=http
        - traefik.http.routers.bitwarden-ui-http.middlewares=redirect-https
        - traefik.http.routers.bitwarden-ui-http.service=bitwarden-ui
        - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
        - traefik.http.routers.bitwarden-websocket-https.rule=Host(`vault.home.tux4all.fr`) && Path(`/notifications/hub`)
        - traefik.http.routers.bitwarden-websocket-https.entrypoints=https
        - traefik.http.routers.bitwarden-websocket-https.tls=true
        - traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket
        - traefik.http.routers.bitwarden-websocket-http.rule=Host(`vault.home.tux4all.fr`) && Path(`/notifications/hub`)
        - traefik.http.routers.bitwarden-websocket-http.entrypoints=http
        - traefik.http.routers.bitwarden-websocket-http.middlewares=redirect-https
        - traefik.http.routers.bitwarden-websocket-http.service=bitwarden-websocket
        - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
    networks:
      - proxy
      - proxy-internal
    environment:
      - SIGNUPS_ALLOWED="false"
      - WEBSOCKET_ENABLED="true"
      - LOG_FILE="/var/log/vaultwarden/vaultwarden.log"
      - LOG_LEVEL=debug
      - TZ="Europe/Paris"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - vaultwarden-logs:/var/log/vaultwarden
      # Data storage AKA DO NOT COMMENT THAT YOU ASS HOLE !!! yep I experienced it ^^
      - $PWD/data/:/data
```
